name: Interpolation
language: python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: launch-telemetry
    required: false
  - name: output
    inputType: OutputTopic
    defaultValue: launch-telemetry-interpolated
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
