name: Launch Telemetry Producer
language: Python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: launch-telemetry
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
