name: Rocket visualization
language: python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: launch-telemetry-xy
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
