name: Position XY calculation
language: python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: launch-telemetry-interpolated
    required: false
  - name: output
    inputType: OutputTopic
    defaultValue: launch-telemetry-xy
    required: false
  - name: test
    inputType: Secret
    description: ''
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
